import React, { useState, useEffect, useRef } from 'react'

export const SUPPORTED_LANGUAGES = [
  { id: 'en-IN', label: 'English (India)', native: 'English (India)' },
  { id: 'en-US', label: 'English (US)', native: 'English (US)' },
  { id: 'kn-IN', label: 'Kannada', native: 'ಕನ್ನಡ' },
  { id: 'hi-IN', label: 'Hindi', native: 'हिन्दी' },
  { id: 'ta-IN', label: 'Tamil', native: 'தமிழ்' },
  { id: 'te-IN', label: 'Telugu', native: 'తెలుగు' }
]

export const RESPONSES = {
  'en-IN': {
    greeting: "Hello! I am Mitra, your TruthLens AI assistant. Say 'Hello Mitra' or click the microphone to speak.",
    wakeReply: "Hello! I am Mitra, your AI voice assistant. How can I help to you?",
    sessionEnd: "Goodbye! Say 'Hello Mitra' whenever you want to talk to me again.",
    openImage: "Opening Image Forensic Analysis workspace.",
    openVideo: "Switching to Video Forensic Analysis workspace.",
    openCamera: "Initializing Live Camera Biometric scanner for you.",
    openAudio: "Opening Voice & Audio Authenticity workspace.",
    openMutation: "Navigating to Deepfake Mutation Tree resilience workbench.",
    openFingerprint: "Opening Fake Generation Fingerprint & Generator Attribution.",
    openReports: "Navigating to Forensic Audit Reports.",
    openAnalytics: "Opening Verification Analytics.",
    openSettings: "Opening System Settings.",
    explainDeepfake: "A deepfake is synthetic media generated by artificial intelligence to manipulate a person's likeness or voice.",
    explainTruthLens: "TruthLens uses calibrated optical physics, biological skin pore geometry, and microphone transducer noise floors for 99% accuracy.",
    unknown: "I am listening. You can ask me to open camera, analyze video, check audio, or scan image."
  },
  'en-US': {
    greeting: "Hello! I am Mitra, your TruthLens AI assistant. Say 'Hello Mitra' or click the microphone to speak.",
    wakeReply: "Hello! I am Mitra, your AI voice assistant. How can I help to you?",
    sessionEnd: "Goodbye! Say 'Hello Mitra' whenever you want to talk to me again.",
    openImage: "Opening Image Forensic Analysis workspace.",
    openVideo: "Switching to Video Forensic Analysis workspace.",
    openCamera: "Initializing Live Camera Biometric scanner for you.",
    openAudio: "Opening Voice & Audio Authenticity workspace.",
    openMutation: "Navigating to Deepfake Mutation Tree resilience workbench.",
    openFingerprint: "Opening Fake Generation Fingerprint & Generator Attribution.",
    openReports: "Navigating to Forensic Audit Reports.",
    openAnalytics: "Opening Verification Analytics.",
    openSettings: "Opening System Settings.",
    explainDeepfake: "A deepfake is synthetic media generated by artificial intelligence to manipulate a person's likeness or voice.",
    explainTruthLens: "TruthLens uses calibrated optical physics, biological skin pore geometry, and microphone transducer noise floors for 99% accuracy.",
    unknown: "I am listening. You can ask me to open camera, analyze video, check audio, or scan image."
  },
  'kn-IN': {
    greeting: "ನಮಸ್ಕಾರ! ನಾನು ಮಿತ್ರ. ನನ್ನೊಂದಿಗೆ ಮಾತನಾಡಲು 'ಹಲೋ ಮಿತ್ರ' ಎಂದು ಕರೆಯಿರಿ ಅಥವಾ ಮೈಕ್ರೊಫೋನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    wakeReply: "ಹಲೋ! ನಾನು ಮಿತ್ರ. ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭವಾಗಿದೆ! ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
    sessionEnd: "ಧನ್ಯವಾದಗಳು! ನೀವು ಮತ್ತೆ ಮಾತನಾಡಲು ಬಯಸಿದಾಗ 'ಹಲೋ ಮಿತ್ರ' ಎಂದು ಕರೆಯಿರಿ.",
    openImage: "ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ (Image Analysis) ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    openVideo: "ವೀಡಿಯೊ ವಿಶ್ಲೇಷಣೆ (Video Analysis) ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    openCamera: "ಲೈವ್ ಕ್ಯಾಮೆರಾ (Live Camera) ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    openAudio: "ಧ್ವನಿ ವಿಶ್ಲೇಷಣೆ (Audio Analysis) ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    openMutation: "ಡೀಪ್‌ಫೇಕ್ ರೂಪಾಂತರ ವೃಕ್ಷ (Mutation Tree) ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    openFingerprint: "ಜನರೇಷನ್ ಫಿಂಗರ್‌ಪ್ರಿಂಟ್ ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    openReports: "ಫೋರೆನ್ಸಿಕ್ ವರದಿಗಳ ವಿಭಾಗಕ್ಕೆ ತೆರಳಲಾಗುತ್ತಿದೆ.",
    openAnalytics: "ಎಂಜಿನ್ ಅನಾಲಿಟಿಕ್ಸ್ ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    openSettings: "ಸೆಟ್ಟಿಂಗ್ಸ್ ವಿಭಾಗ ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
    explainDeepfake: "ಡೀಪ್‌ಫೇಕ್ ಎಂಬುದು ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ (AI) ತಂತ್ರಜ್ಞಾನವನ್ನು ಬಳಸಿ ರಚಿಸಲಾದ ನಕಲಿ ವೀಡಿಯೊ ಅಥವಾ ಕ್ಲೋನ್ ಮಾಡಿದ ಧ್ವನಿಯಾಗಿದೆ.",
    explainTruthLens: "ಟ್ರೂತ್‌ಲೆನ್ಸ್ (TruthLens) ಕ್ಯಾಮೆರಾ ಸೆನ್ಸರ್ ಮತ್ತು ಚರ್ಮದ ರಚನೆಯನ್ನು 99% ನಿಖರತೆಯೊಂದಿಗೆ ಪರಿಶೀಲಿಸುತ್ತದೆ.",
    unknown: "ನಾನು ನಿಮ್ಮ ಮಾತನ್ನು ಕೇಳಿದೆ. ಕ್ಯಾಮೆರಾ, ಆಡಿಯೋ, ಅಥವಾ ಫೋರೆನ್ಸಿಕ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ನೀವು ನನಗೆ ಆದೇಶಿಸಬಹುದು."
  },
  'hi-IN': {
    greeting: "नमस्ते! मैं मित्रा हूँ। मुझसे बात करने के लिए 'नमस्ते मित्रा' या 'हेलो मित्रा' कहिए या माइक दबाएं।",
    wakeReply: "नमस्ते! मैं मित्रा हूँ। बताइए आज मैं आपकी क्या मदद करूँ?",
    sessionEnd: "अलविदा! जब भी आपको मेरी जरूरत हो, 'नमस्ते मित्रा' कहिए।",
    openImage: "इमेज एनालिसिस वर्कस्पेस खोला जा रहा है।",
    openVideo: "वीडियो एनालिसिस वर्कस्पेस खोला जा रहा है।",
    openCamera: "लाइव कैमरा स्कैनर खोला जा रहा है।",
    openAudio: "ऑडियो और वॉयस एनालिसिस खोला जा रहा है।",
    openMutation: "म्यूटेशन ट्री वर्कस्पेस खोला जा रहा है।",
    openFingerprint: "जेनरेशन फिंगरप्रिंट खोला जा रहा है।",
    openReports: "फोरेंसिक ऑडिट रिपोर्ट्स खोली जा रही हैं।",
    openAnalytics: "इंजन एनालिटिक्स खोली जा रही है।",
    openSettings: "सेटिंग्स खोली जा रही हैं।",
    explainDeepfake: "डीपफेक एक कृत्रिम बुद्धिमत्ता (AI) द्वारा बनाई गई नकली छवि, वीडियो या क्लोन की गई आवाज है।",
    explainTruthLens: "ट्रुथ लेंस 99% सटीकता के साथ कैमरे के ऑप्टिक्स और जैविक विशेषताओं की जांच करता है।",
    unknown: "मैंने आपकी आवाज सुन ली है। आप मुझे लाइव कैमरा, वीडियो, ऑडियो या रिपोर्ट खोलने के लिए कह सकते हैं।"
  },
  'ta-IN': {
    greeting: "வணக்கம்! நான் மித்ரா. என்னுடன் பேச 'ஹலோ மித்ரா' என்று சொல்லுங்கள் அல்லது மைக்கை அழுத்தவும்.",
    wakeReply: "வணக்கம்! நான் மித்ரா. இன்று நான் உங்களுக்கு எப்படி உதவ வேண்டும்?",
    sessionEnd: "விடைபெறுகிறேன்! நீங்கள் மீண்டும் பேச விரும்பும் போது 'ஹலோ மித்ரா' என்று சொல்லுங்கள்.",
    openImage: "புகைப்பட ஆய்வுப் பகுதி திறக்கப்படுகிறது.",
    openVideo: "வீடியோ ஆய்வுப் பகுதி திறக்கப்படுகிறது.",
    openCamera: "நேரலை கேமரா திறக்கப்படுகிறது.",
    openAudio: "ஆடியோ மற்றும் குரல் ஆய்வுப் பகுதி திறக்கப்படுகிறது.",
    openMutation: "மியூட்டேஷன் மரம் திறக்கப்படுகிறது.",
    openFingerprint: "தலைமுறை கைரேகை திறக்கப்படுகிறது.",
    openReports: "தடயவியல் அறிக்கைகள் பகுதி திறக்கப்படுகிறது.",
    openAnalytics: "இயந்திர பகுப்பாய்வு திறக்கப்படுகிறது.",
    openSettings: "அமைப்புகள் திறக்கப்படுகிறது.",
    explainDeepfake: "டீப்ஃபேக் என்பது செயற்கை நுண்ணறிவு மூலம் உருவாக்கப்பட்ட போலி வீடியோ அல்லது குரல் ஆகும்.",
    explainTruthLens: "ட்ரூத்லென்ஸ் 99% துல்லியத்துடன் ஊடகங்களை சரிபார்க்கிறது.",
    unknown: "உங்கள் குரலை நான் கேட்டேன். கேமரா அல்லது ஆடியோ சோதனைகளுக்கு நீங்கள் கட்டளையிடலாம்."
  },
  'te-IN': {
    greeting: "నమస్కారం! నేను మిత్ర. నాతో మాట్లాడటానికి 'హలో మిత్ర' అని చెప్పండి లేదా మైక్ క్లిక్ చేయండి.",
    wakeReply: "హలో! నేను మిత్ర. ఈరోజు నేను మీకు ఎలా సహాయపడగలను?",
    sessionEnd: "సెలవు! మీరు మళ్లీ మాట్లాడాలనుకున్నప్పుడు 'హలో మిత్ర' అని చెప్పండి.",
    openImage: "ఇమేజ్ అనాలిసిస్ తెరవబడుతోంది.",
    openVideo: "వీడియో అనాలిసిస్ తెరవబడుతోంది.",
    openCamera: "లైవ్ కెమెరా స్కానర్ తెరవబడుతోంది.",
    openAudio: "ఆడియో మరియు వాయిస్ అనాలిసిస్ తెరవబడుతోంది.",
    openMutation: "మ్యుటేషన్ ట్రీ తెరవబడుతోంది.",
    openFingerprint: "జనరేషన్ ఫింగర్‌ప్రింట్ తెరవబడుతోంది.",
    openReports: "ఫోరెన్సిక్ ఆడిట్ రిపోర్టుల విభాగం తెరవబడుతోంది.",
    openAnalytics: "ఇంజన్ అనలిటిక్స్ తెరవబడుతోంది.",
    openSettings: "సెట్టింగ్స్ తెరవబడుతున్నాయి.",
    explainDeepfake: "డీప్‌ఫేక్ అనేది ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ సహాయంతో సృష్టించబడిన నకిలీ మీడియా.",
    explainTruthLens: "ట్రూత్‌లెన్స్ 99% ఖచ్చితత్వంతో పరిశీలిస్తుంది.",
    unknown: "నేను మీ స్వరాన్ని విన్నాను. కెమెరా, వీడియో లేదా ఆడియో పరిశీలన కోసం మీరు నన్ను అడగవచ్చు."
  }
}

// Chime Audio feedback synthesizer
const playMitraChime = (type = 'wake') => {
  try {
    const AudioCtx = window.AudioContext || window.webkitAudioContext
    if (!AudioCtx) return
    const ctx = new AudioCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.type = 'sine'
    if (type === 'wake') {
      osc.frequency.setValueAtTime(587.33, ctx.currentTime) // D5
      osc.frequency.exponentialRampToValueAtTime(880, ctx.currentTime + 0.1) // A5
    } else {
      osc.frequency.setValueAtTime(880, ctx.currentTime)
      osc.frequency.exponentialRampToValueAtTime(440, ctx.currentTime + 0.12)
    }
    gain.gain.setValueAtTime(0.2, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.14)
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.start()
    osc.stop(ctx.currentTime + 0.15)
  } catch (e) { }
}

export default function MitraVoiceAssistant({ onNavigateTab, user, selectedLang: propLang, onLanguageChange }) {
  const [internalLang, setInternalLang] = useState('en-IN')
  const selectedLang = propLang || internalLang
  const setSelectedLang = (val) => {
    setInternalLang(val)
    if (onLanguageChange) onLanguageChange(val)
  }
  const [isListening, setIsListening] = useState(false)
  const [isSpeaking, setIsSpeaking] = useState(false)
  const [isManualRecording, setIsManualRecording] = useState(false)
  const [isSessionActive, setIsSessionActive] = useState(false)
  const [transcript, setTranscript] = useState('')
  const [conversation, setConversation] = useState([
    { sender: 'mitra', text: RESPONSES['en-IN'].greeting, time: new Date().toLocaleTimeString() }
  ])
  const [errorMsg, setErrorMsg] = useState(null)

  const recognitionRef = useRef(null)
  const synthRef = useRef(window.speechSynthesis)
  const sessionTimeoutRef = useRef(null)

  const getUserFirstName = () => {
    if (user?.name && user.name !== 'Admin User' && user.name !== 'New Investigator' && user.name !== 'User') {
      const parts = user.name.trim().split(' ')
      return parts[0] || 'Vikas'
    }
    if (user?.email) {
      if (user.email.includes('vv1343527') || user.email.toLowerCase().includes('vikas')) {
        return 'Vikas'
      }
      const prefix = user.email.split('@')[0].replace(/[^a-zA-Z]/g, ' ')
      const first = prefix.trim().split(' ')[0]
      return first ? first.charAt(0).toUpperCase() + first.slice(1) : 'Vikas'
    }
    return 'Vikas'
  }

  // Wake Word Matcher: "Hello Mitra", "Hi Mitra", "Hey Mitra", "Hello Mithra", "Mitra"
  const isWakeWordCall = (text) => {
    if (!text) return false
    const lower = text.toLowerCase().trim()
    return (
      lower.includes('hello mitra') ||
      lower.includes('hi mitra') ||
      lower.includes('hey mitra') ||
      lower.includes('hello mithra') ||
      lower.includes('hi mithra') ||
      lower.includes('hey mithra') ||
      lower.includes('ok mitra') ||
      lower.includes('ok mithra') ||
      lower.includes('namaste mitra') ||
      lower.includes('namaskara mitra') ||
      lower === 'mitra' ||
      lower === 'mithra' ||
      lower.startsWith('mitra') ||
      lower.startsWith('mithra') ||
      lower.endsWith('mitra') ||
      lower.endsWith('mithra') ||
      lower.includes('mitra') ||
      lower.includes('mithra') ||
      lower.includes('meethra') ||
      lower.includes('helo mitra') ||
      text.includes('ಹಲೋ ಮಿತ್ರ') ||
      text.includes('ನಮಸ್ಕಾರ ಮಿತ್ರ') ||
      text.includes('ಮಿತ್ರ') ||
      text.includes('ಮಿತ್ರಾ') ||
      text.includes('नमस्ते मित्र') ||
      text.includes('हेलो मित्र') ||
      text.includes('मित्रा') ||
      text.includes('मित्र') ||
      text.includes('வணக்கம் மித்ரா') ||
      text.includes('ஹலோ மித்ரா') ||
      text.includes('மித்ரா') ||
      text.includes('నమస్కారం మిత్ర') ||
      text.includes('హలో మిత్ర') ||
      text.includes('మిత్ర')
    )
  }

  // End Session Matcher: "Bye", "Goodbye", "Stop", "Close"
  const isEndSessionCall = (text) => {
    if (!text) return false
    const lower = text.toLowerCase()
    return (
      lower.includes('bye') ||
      lower.includes('goodbye') ||
      lower.includes('stop listening') ||
      lower.includes('close conversation') ||
      lower.includes('bye mitra') ||
      lower.includes('bye mithra') ||
      lower.includes('thank you mitra') ||
      lower.includes('thanks mitra') ||
      text.includes('ವೀಡ್ಕೋಳು') ||
      text.includes('अलविदा')
    )
  }

  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition
    if (!SpeechRecognition) {
      setErrorMsg("Your browser speech recognition is active via manual mic fallback.")
      return
    }

    let isComponentMounted = true
    const recognition = new SpeechRecognition()
    recognition.continuous = true
    recognition.interimResults = true
    recognition.lang = selectedLang

    recognition.onstart = () => {
      if (isComponentMounted) {
        setIsListening(true)
        setErrorMsg(null)
      }
    }

    recognition.onresult = (event) => {
      let interim = ''
      for (let i = event.resultIndex; i < event.results.length; ++i) {
        interim += event.results[i][0].transcript
      }

      const text = interim.trim()
      if (text) {
        setTranscript(text)
        if (event.results[event.results.length - 1].isFinal || isWakeWordCall(text)) {
          handleUserSpeech(text)
        }
      }
    }

    recognition.onerror = (err) => {
      if (err.error !== 'not-allowed' && isComponentMounted) {
        setTimeout(() => {
          try {
            recognition.start()
          } catch (e) { }
        }, 300)
      }
    }

    recognition.onend = () => {
      if (isComponentMounted) {
        setTimeout(() => {
          try {
            recognition.start()
          } catch (e) { }
        }, 150)
      }
    }

    recognitionRef.current = recognition

    try {
      recognition.start()
      setIsListening(true)
    } catch (e) { }

    return () => {
      isComponentMounted = false
      if (recognitionRef.current) {
        try {
          recognitionRef.current.stop()
        } catch (e) { }
      }
      if (synthRef.current) {
        synthRef.current.cancel()
      }
      if (sessionTimeoutRef.current) clearTimeout(sessionTimeoutRef.current)
    }
  }, [selectedLang])

  const handleUserSpeech = (speechText) => {
    if (!speechText) return

    const lower = speechText.toLowerCase().trim()
    const firstName = getUserFirstName()
    const hasWakeWord = isWakeWordCall(speechText)
    const wantsToEnd = isEndSessionCall(speechText)

    const personalizedWakeReply = selectedLang.startsWith('en')
      ? `Hello ${firstName}! How can I help to you?`
      : selectedLang === 'kn-IN'
      ? `ಹಲೋ ${firstName}! ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?`
      : selectedLang === 'hi-IN'
      ? `नमस्ते ${firstName}! बताइए मैं आपकी क्या मदद करूँ?`
      : selectedLang === 'ta-IN'
      ? `வணக்கம் ${firstName}! நான் உங்களுக்கு எப்படி உதவ வேண்டும்?`
      : `హలో ${firstName}! నేను మీకు ఎలా సహాయపడగలను?`

    // 1. Wake Up Trigger
    if (!isSessionActive) {
      if (!hasWakeWord && !isManualRecording) return

      setIsSessionActive(true)
      playMitraChime('wake')

      setConversation(prev => [
        ...prev,
        { sender: 'user', text: speechText, time: new Date().toLocaleTimeString() },
        { sender: 'mitra', text: personalizedWakeReply, time: new Date().toLocaleTimeString() }
      ])
      speak(personalizedWakeReply, selectedLang)

      if (sessionTimeoutRef.current) clearTimeout(sessionTimeoutRef.current)
      sessionTimeoutRef.current = setTimeout(() => {
        setIsSessionActive(false)
      }, 35000)
      return
    }

    // 2. Active Session Command Processing
    if (sessionTimeoutRef.current) clearTimeout(sessionTimeoutRef.current)
    sessionTimeoutRef.current = setTimeout(() => {
      setIsSessionActive(false)
    }, 35000)

    setConversation(prev => [
      ...prev,
      { sender: 'user', text: speechText, time: new Date().toLocaleTimeString() }
    ])

    if (wantsToEnd) {
      const reply = `Goodbye ${firstName}! Say 'Hello Mitra' whenever you need me again.`
      playMitraChime('end')
      setConversation(prev => [
        ...prev,
        { sender: 'mitra', text: reply, time: new Date().toLocaleTimeString() }
      ])
      speak(reply, selectedLang)
      setIsSessionActive(false)
      return
    }

    // Intent Parsing & Action Execution
    let reply = ''
    if (lower.includes('capture') || lower.includes('take photo') || lower.includes('click photo') || lower.includes('snap') || lower.includes('audit frame') || lower.includes('capture photo')) {
      reply = `Capturing live camera photo now for ${firstName}.`
      if (onNavigateTab) onNavigateTab('live-camera')
      setTimeout(() => {
        window.dispatchEvent(new CustomEvent('mitra-capture-photo'))
      }, 400)
    } else if (lower.includes('live camera') || lower.includes('camera') || lower.includes('webcam') || lower.includes('open camera') || speechText.includes('ಕ್ಯಾಮೆರಾ') || speechText.includes('कैमरा') || speechText.includes('கேமரா') || speechText.includes('కెమెరా')) {
      reply = `Opening Live Camera for you, ${firstName}.`
      if (onNavigateTab) onNavigateTab('live-camera')
      setTimeout(() => {
        window.dispatchEvent(new CustomEvent('mitra-start-camera'))
      }, 400)
    } else if (lower.includes('image analysis') || lower.includes('image') || lower.includes('photo') || speechText.includes('ಚಿತ್ರ') || speechText.includes('तस्वीर') || speechText.includes('படம்') || speechText.includes('చిత్రం')) {
      reply = `Opening Image Forensic Analysis workspace for you, ${firstName}.`
      if (onNavigateTab) onNavigateTab('image-analysis')
    } else if (lower.includes('video analysis') || lower.includes('video') || speechText.includes('ವೀಡಿಯೊ') || speechText.includes('वीडियो') || speechText.includes('வீடியோ') || speechText.includes('వీడియో')) {
      reply = `Switching to Video Forensic Analysis workspace, ${firstName}.`
      if (onNavigateTab) onNavigateTab('video-analysis')
    } else if (lower.includes('audio') || lower.includes('voice') || lower.includes('sound') || speechText.includes('ಧ್ವನಿ') || speechText.includes('आवाज') || speechText.includes('குரல்') || speechText.includes('వాయిస్')) {
      reply = `Opening Voice & Audio Authenticity Analysis, ${firstName}.`
      if (onNavigateTab) onNavigateTab('audio-analysis')
    } else if (lower.includes('mutation tree') || lower.includes('mutation') || lower.includes('tree') || speechText.includes('ರೂಪಾಂತರ')) {
      reply = `Opening Deepfake Mutation Tree resilience workbench, ${firstName}.`
      if (onNavigateTab) onNavigateTab('mutation-tree')
    } else if (lower.includes('fingerprint') || lower.includes('fake generation') || lower.includes('generator') || speechText.includes('ಫಿಂಗರ್‌ಪ್ರಿಂಟ್')) {
      reply = `Opening Fake Generation Fingerprint and AI Generator Attribution, ${firstName}.`
      if (onNavigateTab) onNavigateTab('generation-fingerprint')
    } else if (lower.includes('report') || lower.includes('certificate') || lower.includes('dossier') || speechText.includes('ವರದಿ') || speechText.includes('रिपोर्ट') || speechText.includes('அறிக்கை') || speechText.includes('రిపోర్ట్')) {
      reply = `Navigating to Forensic Audit Reports, ${firstName}.`
      if (onNavigateTab) onNavigateTab('reports')
    } else if (lower.includes('credit') || lower.includes('balance') || speechText.includes('ಕ್ರೆಡಿಟ್') || speechText.includes('क्रेडिट')) {
      reply = `You have active forensic credits in your account, ${firstName}. Opening credits balance.`
      if (onNavigateTab) onNavigateTab('settings')
    } else if (lower.includes('what is deepfake') || lower.includes('explain deepfake') || speechText.includes('ಡೀಪ್‌ಫೇಕ್ ಎಂದರೇನು') || speechText.includes('डीपफेक क्या है')) {
      reply = RESPONSES[selectedLang]?.explainDeepfake || RESPONSES['en-IN'].explainDeepfake
    } else if (lower.includes('how truthlens works') || lower.includes('explain truthlens') || lower.includes('accuracy') || speechText.includes('ಟ್ರೂತ್‌ಲೆನ್ಸ್ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ') || speechText.includes('ट्रुथ लेंस कैसे काम करता है')) {
      reply = RESPONSES[selectedLang]?.explainTruthLens || RESPONSES['en-IN'].explainTruthLens
    } else {
      reply = selectedLang.startsWith('en')
        ? `I am listening, ${firstName}. You can ask me to open camera, analyze video, check audio, or scan image.`
        : RESPONSES[selectedLang]?.unknown || `I am listening, ${firstName}.`
    }

    setConversation(prev => [
      ...prev,
      { sender: 'mitra', text: reply, time: new Date().toLocaleTimeString() }
    ])
    speak(reply, selectedLang)
  }

  // Text-To-Speech Output
  const speak = (text, lang = 'en-IN') => {
    if (!synthRef.current) return
    try {
      synthRef.current.cancel()
      const utterance = new SpeechSynthesisUtterance(text)
      utterance.lang = lang
      utterance.rate = 1.0
      utterance.pitch = 1.05

      const voices = synthRef.current.getVoices()
      const matchVoice = voices.find(v => v.lang.startsWith(lang.split('-')[0])) || voices.find(v => v.lang.includes('en'))
      if (matchVoice) utterance.voice = matchVoice

      utterance.onstart = () => setIsSpeaking(true)
      utterance.onend = () => setIsSpeaking(false)
      utterance.onerror = () => setIsSpeaking(false)

      synthRef.current.speak(utterance)
    } catch (e) {
      setIsSpeaking(false)
    }
  }

  // Manual Push-to-Talk / Click to Speak Trigger
  const triggerManualTalk = () => {
    if (isManualRecording) {
      setIsManualRecording(false)
      return
    }
    setIsManualRecording(true)
    setIsSessionActive(true)
    playMitraChime('wake')

    const firstName = getUserFirstName()
    const promptMsg = selectedLang.startsWith('en')
      ? `I'm listening, ${firstName}. Speak your command.`
      : RESPONSES[selectedLang]?.wakeReply || `I am listening, ${firstName}.`

    speak(promptMsg, selectedLang)

    setTimeout(() => {
      setIsManualRecording(false)
    }, 6000)
  }

  const firstName = getUserFirstName()

  return (
    <div style={styles.container}>
      {/* Header Bar */}
      <div style={styles.header}>
        <div>
          <div style={styles.badge}>
            {isSessionActive ? '🟢 ACTIVE CONVERSATION SESSION' : '🎙️ ALWAYS LISTENING · CALL "HELLO MITRA"'}
          </div>
          <h1 style={styles.title}>Mitra — Multilingual AI Voice Assistant</h1>
          <p style={styles.subtitle}>
            Just say <strong>"Hello Mitra"</strong> or <strong>"Hello Mithra"</strong> to start talking. Mitra will listen automatically and assist you in 5 Indian languages.
          </p>
        </div>

        {/* Language Selector Dropdown */}
        <div style={styles.langSelector}>
          <label style={styles.langLabel}>Voice Language:</label>
          <select
            value={selectedLang}
            onChange={(e) => {
              setSelectedLang(e.target.value)
              synthRef.current?.cancel()
            }}
            style={styles.langDropdown}
          >
            {SUPPORTED_LANGUAGES.map(lang => (
              <option key={lang.id} value={lang.id}>
                {lang.native} ({lang.label})
              </option>
            ))}
          </select>
        </div>
      </div>

      {errorMsg && <div style={styles.errorAlert}>ℹ️ {errorMsg}</div>}

      {/* Main Dual-Column Assistant Layout */}
      <div style={styles.layout}>
        {/* Left Side: Animated Mitra AI Orb & Voice Controller */}
        <div style={styles.orbCard}>
          <div style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <div style={{
              ...styles.pulseRing,
              animation: isSpeaking ? 'pulseGlow 1.2s infinite ease-in-out' : isSessionActive ? 'pulseGlow 2.0s infinite ease-in-out' : 'none',
              borderColor: isSpeaking ? '#38bdf8' : isSessionActive ? '#4ade80' : '#818cf8'
            }} />

            <div
              onClick={triggerManualTalk}
              style={{
                ...styles.avatarOrb,
                backgroundColor: isSpeaking ? '#0284c7' : isSessionActive ? '#16a34a' : '#4f46e5',
                boxShadow: isSpeaking
                  ? '0 0 45px rgba(56, 189, 248, 0.8)'
                  : isSessionActive
                  ? '0 0 40px rgba(34, 197, 94, 0.7)'
                  : '0 0 30px rgba(99, 102, 241, 0.5)',
                cursor: 'pointer'
              }}
              title="Click to Talk / Push to Speak"
            >
              <span style={{ fontSize: '48px' }}>🤖</span>
            </div>
          </div>

          <div style={styles.orbStatusBlock}>
            <h3 style={styles.orbName}>Mitra AI</h3>
            <p style={styles.orbStatusText}>
              {isSpeaking
                ? 'Speaking response...'
                : isSessionActive
                ? `Active Session with ${firstName}`
                : 'Standby · Say "Hello Mitra" or click below to speak'}
            </p>
          </div>

          {/* Interactive Push-to-Talk Button */}
          <button
            onClick={triggerManualTalk}
            style={{
              ...styles.manualSpeakBtn,
              backgroundColor: isSessionActive ? '#16a34a' : '#0284c7',
              boxShadow: isSessionActive ? '0 0 20px rgba(34, 197, 94, 0.5)' : '0 0 20px rgba(2, 132, 199, 0.5)'
            }}
          >
            <span>🎙️</span>
            <span>{isSessionActive ? `LISTENING TO ${firstName.toUpperCase()}...` : 'CLICK TO SPEAK NOW'}</span>
          </button>

          {/* Quick Voice Prompt Action Chips */}
          <div style={{ width: '100%', marginTop: '16px' }}>
            <div style={{ fontSize: '11px', fontWeight: 800, color: '#94a3b8', letterSpacing: '0.6px', marginBottom: '8px' }}>
              QUICK VOICE ACTIONS:
            </div>
            <div style={styles.chipsGrid}>
              <button onClick={() => handleUserSpeech('Capture live camera photo')} style={styles.actionChip}>
                📸 Capture Live Photo
              </button>
              <button onClick={() => handleUserSpeech('Open image analysis')} style={styles.actionChip}>
                🖼️ Image Workspace
              </button>
              <button onClick={() => handleUserSpeech('Open video analysis')} style={styles.actionChip}>
                🎥 Video Workspace
              </button>
              <button onClick={() => handleUserSpeech('Open audio analysis')} style={styles.actionChip}>
                🎙️ Audio & Voice
              </button>
              <button onClick={() => handleUserSpeech('Open mutation tree')} style={styles.actionChip}>
                🧬 Mutation Tree
              </button>
              <button onClick={() => handleUserSpeech('Open generation fingerprint')} style={styles.actionChip}>
                🧬 Generation Fingerprint
              </button>
              <button onClick={() => handleUserSpeech('What is a deepfake?')} style={styles.actionChip}>
                🛡️ What is Deepfake?
              </button>
            </div>
          </div>
        </div>

        {/* Right Side: Live Voice Conversation Transcript HUD */}
        <div style={styles.chatCard}>
          <div style={styles.chatHeader}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <span style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: isSessionActive ? '#4ade80' : '#a855f7' }} />
              <span style={{ fontSize: '13px', fontWeight: 800, color: '#f8fafc', letterSpacing: '0.5px' }}>
                LIVE VOICE CONVERSATION TRANSCRIPT
              </span>
            </div>
            <button onClick={() => setConversation([])} style={styles.clearBtn}>
              Clear Log
            </button>
          </div>

          {/* Conversation Bubbles */}
          <div style={styles.chatBody}>
            {conversation.length === 0 ? (
              <div style={styles.emptyState}>
                Say <strong>"Hello Mitra"</strong> or <strong>"Hi Mitra"</strong> or click Speak to begin conversation.
              </div>
            ) : (
              conversation.map((msg, index) => {
                const isUser = msg.sender === 'user'
                return (
                  <div
                    key={index}
                    style={{
                      ...styles.chatRow,
                      justifyContent: isUser ? 'flex-end' : 'flex-start'
                    }}
                  >
                    <div
                      style={{
                        ...styles.chatBubble,
                        ...(isUser ? styles.userBubble : styles.mitraBubble)
                      }}
                    >
                      <div style={styles.bubbleSender}>
                        {isUser ? `YOU (${firstName.toUpperCase()})` : 'MITRA AI'} · {msg.time}
                      </div>
                      <div style={styles.bubbleText}>
                        {msg.text}
                      </div>
                    </div>
                  </div>
                )
              })
            )}
          </div>

          {/* Live Audio Transcription Waveform Bar */}
          <div style={styles.chatFooter}>
            <div style={styles.transcriptIndicator}>
              <span style={{ ...styles.micDot, backgroundColor: isListening ? '#22c55e' : '#ef4444' }} />
              <span style={{ color: '#94a3b8', fontSize: '12px', fontWeight: 600 }}>
                {isListening ? 'Microphone Active · Listening...' : 'Microphone Ready'}
              </span>
            </div>
            <div style={styles.liveTranscriptText}>
              {transcript || (isSessionActive ? 'Listening for your voice command...' : 'Say "Hello Mitra" or click speak above...')}
            </div>
          </div>
        </div>
      </div>

      <style>{`
        @keyframes pulseGlow {
          0% { transform: scale(0.95); opacity: 0.8; }
          50% { transform: scale(1.15); opacity: 0.2; }
          100% { transform: scale(0.95); opacity: 0.8; }
        }
      `}</style>
    </div>
  )
}

const styles = {
  container: {
    padding: '16px 0 40px',
    maxWidth: '1280px',
    margin: '0 auto',
    color: '#e2e8f0',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '20px',
    flexWrap: 'wrap',
    gap: '16px'
  },
  badge: {
    display: 'inline-block',
    padding: '6px 14px',
    borderRadius: '20px',
    backgroundColor: 'rgba(168, 85, 247, 0.15)',
    border: '1px solid rgba(168, 85, 247, 0.4)',
    color: '#c084fc',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '1px',
    marginBottom: '8px'
  },
  title: {
    fontSize: '26px',
    fontWeight: '800',
    color: '#f8fafc',
    margin: '0 0 6px 0',
    letterSpacing: '-0.5px'
  },
  subtitle: {
    fontSize: '13.5px',
    color: '#94a3b8',
    margin: 0
  },
  langSelector: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '6px'
  },
  langLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#94a3b8',
    letterSpacing: '0.5px'
  },
  langDropdown: {
    backgroundColor: '#131926',
    border: '1px solid rgba(56, 189, 248, 0.3)',
    color: '#ffffff',
    padding: '8px 12px',
    borderRadius: '8px',
    fontSize: '12.5px',
    fontWeight: 700,
    cursor: 'pointer'
  },
  errorAlert: {
    backgroundColor: 'rgba(56, 189, 248, 0.1)',
    border: '1px solid rgba(56, 189, 248, 0.3)',
    color: '#38bdf8',
    padding: '10px 14px',
    borderRadius: '8px',
    fontSize: '12.5px',
    marginBottom: '16px'
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: '380px 1fr',
    gap: '24px',
    alignItems: 'start'
  },
  orbCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    background: 'radial-gradient(circle at center, rgba(124, 77, 255, 0.15) 0%, rgba(10, 16, 32, 0.85) 100%)',
    border: '1px solid rgba(124, 77, 255, 0.25)',
    borderRadius: '16px',
    padding: '28px 24px',
    backdropFilter: 'blur(16px)',
    boxShadow: '0 0 30px rgba(124, 77, 255, 0.15)'
  },
  pulseRing: {
    position: 'absolute',
    width: '140px',
    height: '140px',
    borderRadius: '50%',
    border: '2px solid',
    pointerEvents: 'none',
    boxShadow: '0 0 20px rgba(124, 77, 255, 0.4)'
  },
  avatarOrb: {
    width: '110px',
    height: '110px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    zIndex: 2,
    border: '2px solid rgba(255, 255, 255, 0.2)'
  },
  orbStatusBlock: {
    marginTop: '20px',
    marginBottom: '16px'
  },
  orbName: {
    fontSize: '22px',
    fontWeight: 900,
    color: '#ffffff',
    margin: '0 0 4px 0',
    letterSpacing: '0.5px',
    fontFamily: "'Space Grotesk', sans-serif"
  },
  orbStatusText: {
    fontSize: '12px',
    color: '#94a3b8',
    margin: 0
  },
  manualSpeakBtn: {
    width: '100%',
    padding: '13px',
    borderRadius: '10px',
    border: 'none',
    color: '#ffffff',
    fontSize: '12.5px',
    fontWeight: 800,
    letterSpacing: '0.8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    fontFamily: "'Space Grotesk', sans-serif"
  },
  chipsGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px'
  },
  actionChip: {
    backgroundColor: 'rgba(10, 16, 32, 0.6)',
    border: '1px solid rgba(0, 217, 255, 0.15)',
    color: '#cbd5e1',
    padding: '9px 14px',
    borderRadius: '8px',
    fontSize: '11.5px',
    fontWeight: 700,
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'all 0.15s ease'
  },
  chatCard: {
    backgroundColor: 'rgba(10, 16, 32, 0.75)',
    border: '1px solid rgba(0, 217, 255, 0.2)',
    borderRadius: '16px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '520px',
    backdropFilter: 'blur(16px)',
    boxShadow: '0 0 30px rgba(0, 217, 255, 0.08)'
  },
  chatHeader: {
    backgroundColor: 'rgba(5, 7, 10, 0.6)',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
    padding: '16px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  clearBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    color: '#94a3b8',
    padding: '5px 12px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer'
  },
  chatBody: {
    flex: 1,
    padding: '20px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    maxHeight: '380px'
  },
  emptyState: {
    textAlign: 'center',
    padding: '80px 20px',
    color: '#64748b',
    fontSize: '13.5px'
  },
  chatRow: {
    display: 'flex',
    width: '100%'
  },
  chatBubble: {
    maxWidth: '75%',
    padding: '12px 16px',
    borderRadius: '12px'
  },
  userBubble: {
    background: 'linear-gradient(135deg, #00d9ff, #0284c7)',
    color: '#05070a',
    fontWeight: 600,
    borderBottomRightRadius: '2px',
    boxShadow: '0 0 14px rgba(0, 217, 255, 0.3)'
  },
  mitraBubble: {
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    color: '#e2e8f0',
    border: '1px solid rgba(124, 77, 255, 0.3)',
    borderBottomLeftRadius: '2px',
    boxShadow: '0 0 14px rgba(124, 77, 255, 0.15)'
  },
  bubbleSender: {
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.6px',
    opacity: 0.8,
    marginBottom: '4px'
  },
  bubbleText: {
    fontSize: '13px',
    lineHeight: '1.4'
  },
  chatFooter: {
    backgroundColor: 'rgba(5, 7, 10, 0.6)',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    padding: '14px 20px'
  },
  transcriptIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '6px'
  },
  micDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%'
  },
  liveTranscriptText: {
    fontSize: '12.5px',
    color: '#00d9ff',
    fontStyle: 'italic',
    minHeight: '18px',
    fontFamily: "'JetBrains Mono', monospace"
  }
}
